-- =============================================================================
-- Migration: 001_initial_schema.sql
-- Description: Orion AI Copilot Database Baseline (v0.5 MVP)
-- Core Invariants:
--   - pgcrypto (gen_random_uuid), pgvector(1536), pg_trgm
--   - Dual 1536-dim embeddings: text_embedding + image_embedding (gemini-embedding-2)
--   - Generated search_tsv for native full-text search
--   - Dummy telemetry is generated by the API and is not persisted
--   - Ingestion jobs queue with FOR UPDATE SKIP LOCKED support
--   - App users with role mapping (viewer | operator | admin)
--   - Private storage paths only; RLS default-deny with role-scoped policies
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- -----------------------------------------------------------------------------
-- Helper: Updated_At Trigger
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 1. App Users (Role mapping for authenticated Supabase users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer', 'operator', 'admin')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TRIGGER trg_app_users_updated_at BEFORE UPDATE ON app_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- 2. Machine Registry
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS machines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    machine_key TEXT UNIQUE NOT NULL,             -- e.g. 'orion_1', 'orion_2'
    name TEXT NOT NULL,                           -- 'Orion VFFS Machine #1'
    model TEXT DEFAULT '4PPC80.121E-10A',
    manufacturer TEXT DEFAULT 'B&R Industrial Automation GmbH',
    timezone TEXT DEFAULT 'UTC',
    is_active BOOLEAN DEFAULT true,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TRIGGER trg_machines_updated_at BEFORE UPDATE ON machines FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- 4. Document Library, Ingestion Jobs & Manual Pages
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS manual_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_key TEXT NOT NULL,                     -- 'orion_vffs'
    revision TEXT NOT NULL,                       -- 'rev3.1'
    sha256 TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    filename TEXT NOT NULL,
    total_pages INT NOT NULL DEFAULT 0,
    parser_version TEXT DEFAULT '1.0',
    pdf_storage_path TEXT NOT NULL,              -- Private bucket path
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
    -- New revisions are staged until an admin explicitly activates them.
    is_active BOOLEAN DEFAULT false,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TRIGGER trg_manual_documents_updated_at BEFORE UPDATE ON manual_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Enforce exactly one active revision per document family
CREATE UNIQUE INDEX IF NOT EXISTS uq_one_active_revision_per_family 
    ON manual_documents (family_key) 
    WHERE is_active = true;

-- Background worker queue for PDF ingestion
CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL REFERENCES manual_documents(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    attempt_count INT NOT NULL DEFAULT 0,
    leased_until TIMESTAMPTZ,                        -- crash recovery: expired lease = retryable
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TRIGGER trg_ingestion_jobs_updated_at BEFORE UPDATE ON ingestion_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_pending 
    ON ingestion_jobs(status, created_at) 
    WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS manual_pages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID NOT NULL REFERENCES manual_documents(id) ON DELETE CASCADE,
    page_number INT NOT NULL,
    storage_path TEXT NOT NULL,                   -- Private path only
    
    page_type TEXT DEFAULT 'unknown',
    subsystem TEXT DEFAULT 'unknown',
    error_codes_indexed TEXT[] DEFAULT '{}',
    component_tags TEXT[] DEFAULT '{}',
    summary TEXT,
    extracted_text TEXT NOT NULL DEFAULT '',
    
    -- Dual Gemini Embedding 2 vectors (1536-dim)
    text_embedding vector(1536),
    image_embedding vector(1536),
    embedding_profile TEXT NOT NULL DEFAULT 'gemini-embedding-2',
    
    -- Full-text search tsvector (generated & stored)
    search_tsv tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(summary, '') || ' ' || extracted_text)
    ) STORED,
    
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_manual_pages_doc_num UNIQUE (document_id, page_number)
);

CREATE INDEX IF NOT EXISTS idx_manual_pages_text_hnsw 
    ON manual_pages USING hnsw (text_embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_manual_pages_image_hnsw 
    ON manual_pages USING hnsw (image_embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_manual_pages_tsv 
    ON manual_pages USING gin (search_tsv);

CREATE INDEX IF NOT EXISTS idx_manual_pages_error_codes 
    ON manual_pages USING gin (error_codes_indexed);

CREATE INDEX IF NOT EXISTS idx_manual_pages_components 
    ON manual_pages USING gin (component_tags);

-- -----------------------------------------------------------------------------
-- 5. Conversations & Evidence-Linked Messages
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    machine_id UUID REFERENCES machines(id) ON DELETE SET NULL,
    title TEXT DEFAULT 'Diagnostic Session',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    evidence JSONB DEFAULT '{}'::jsonb,           -- {record_keys: [], event_ids: [], page_ids: [], scores: [], model: "", latency_ms: 0}
    created_at TIMESTAMPTZ DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 6. Row Level Security (RLS) & Policies
-- -----------------------------------------------------------------------------
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Revoke default public execution & access
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, anon;

-- Application data is API-only. The browser uses Supabase for Auth, not table access.
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Service-role policies support server-side Auth/Storage administration.
CREATE POLICY "service_role_all_machines" ON machines FOR ALL TO service_role USING (true);
CREATE POLICY "service_role_all_docs" ON manual_documents FOR ALL TO service_role USING (true);
CREATE POLICY "service_role_all_jobs" ON ingestion_jobs FOR ALL TO service_role USING (true);
CREATE POLICY "service_role_all_pages" ON manual_pages FOR ALL TO service_role USING (true);
CREATE POLICY "service_role_all_conv" ON conversations FOR ALL TO service_role USING (true);
CREATE POLICY "service_role_all_msg" ON messages FOR ALL TO service_role USING (true);

-- -----------------------------------------------------------------------------
-- 7. Seed Default Machines
-- -----------------------------------------------------------------------------
INSERT INTO machines (machine_key, name, model, manufacturer, is_active)
VALUES 
    ('orion_1', 'Orion VFFS #1', '4PPC80.121E-10A', 'B&R Industrial Automation GmbH', true),
    ('orion_2', 'Orion VFFS #2', '4PPC80.121E-10A', 'B&R Industrial Automation GmbH', true)
ON CONFLICT (machine_key) DO NOTHING;
